openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:9090/v1.0
paths:
  /pets:
    get:
      summary: List all pets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      required:
        - name
      properties:
        name:
          type: string
          example: fluffy
        tag:
          type: string
          example: red
        id:
          type: integer
          format: int64
          readOnly: true
          example: 1
        last_updated:
          type: string
          readOnly: true
          example: 2019-01-16T23:52:54.309102Z

    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
